before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./
  binary: pftaskqueue
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  - 386
  flags:
  - -a
  - -tags
  - netgo
  - -installsuffix
  - netgo
  ldflags:
  - -s -w -X github.com/pfnet-research/pftaskqueue/cmd.Version={{.Version}} -X github.com/pfnet-research/pftaskqueue/cmd.Revision={{.ShortCommit}} -extldflags "-static"

dockers:
- image_templates: ["ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-amd64"]
  dockerfile: Dockerfile
  goarch: amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/pfnet-research/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/pfnet-research/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-arm64v8"]
  dockerfile: Dockerfile
  goarch: arm64
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/pfnet-research/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/pfnet-research/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
- name_template: ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}
  image_templates:
  - ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-amd64
  - ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-arm64v8
- name_template: ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev{{else}}release{{end}}:latest
  image_templates:
  - ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-amd64
  - ghcr.io/pfnet-research/{{ .ProjectName }}/{{ if .IsSnapshot }}dev:v{{ incpatch .Version }}-alpha-{{ .ShortCommit }}{{else}}release:v{{ .Version }}{{end}}-arm64v8

snapshot:
  name_template: '{{ incpatch .Version }}-alpha-{{ .ShortCommit }}'

changelog:
  skip: true
